[package]
name = "godot-netlink-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
bytes.workspace = true
thiserror.workspace = true
bitflags.workspace = true
async-trait.workspace = true
tokio = { workspace = true }
serde = { workspace = true }
serde_json.workspace = true
uuid = { workspace = true }

[dev-dependencies]
